<?php

/**
 * Copyright 2018 Adobe
 * All Rights Reserved.
 */
declare (strict_types=1);
namespace Magento\Functional_Testing_Framework\Console;

use Magento\Functional_Testing_Framework\Exceptions\Test_Framework_Exception;
use Magento\Functional_Testing_Framework\Util\Path\File_Path_Formatter;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\Input_Interface;
use Symfony\Component\Console\Input\Input_Option;
use Symfony\Component\Console\Output\Output_Interface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Finder\Finder;
class Clean_Project_Command extends Command
{
    private const SUCCESS_EXIT_CODE = 0;
    /**
     * Configures the current command.
     */
    protected function configure(): void
    {
        $this->set_name('reset')->set_description('This command will clean any configuration files from the environment (not including .env), as well as generated artifacts.')->add_option('hard', null, Input_Option::VALUE_NONE, 'parameter to force reset of configuration files.');
    }
    /**
     * Executes the current command.
     *
     * @throws \Symfony\Component\Console\Exception\LogicException
     * @throws TestFrameworkException
     */
    protected function execute(Input_Interface $input, Output_Interface $output): int
    {
        $config_files = [
            // codeception.yml file for top level config
            File_Path_Formatter::format(TESTS_BP) . 'codeception.yml',
            // functional.suite.yml for test execution config
            File_Path_Formatter::format(TESTS_BP) . 'tests' . DIRECTORY_SEPARATOR . 'functional.suite.yml',
            // Acceptance Tester Actions generated by codeception
            File_Path_Formatter::format(FW_BP) . 'src/Magento/FunctionalTestingFramework/_generated',
            // AcceptanceTester Class generated by codeception
            File_Path_Formatter::format(FW_BP) . 'src/Magento/FunctionalTestingFramework/AcceptanceTester.php',
        ];
        $generated_files = [File_Path_Formatter::format(TESTS_MODULE_PATH) . '_generated'];
        $is_hard_reset = $input->get_option('hard');
        $file_system = new Filesystem();
        $finder = new Finder();
        $finder->files()->name('*.php')->in(realpath(File_Path_Formatter::format(FW_BP) . 'src/Magento/FunctionalTestingFramework/Group/'));
        $files_for_removal = [];
        // include config files if user specifies a hard reset for deletion
        if ($is_hard_reset) {
            $files_for_removal = array_merge($files_for_removal, $config_files);
        }
        // include the files mftf generates during test execution in TESTS_BP for deletion
        $files_for_removal = array_merge($files_for_removal, $generated_files);
        if ($output->is_verbose()) {
            $output->writeln('Deleting Files:');
        }
        // delete any suite based group files
        foreach ($finder->files() as $file) {
            if ($output->is_verbose()) {
                $output->writeln($file->get_real_path());
            }
            $file_system->remove($file);
        }
        // delete files specified for removal
        foreach ($files_for_removal as $file_for_removal) {
            if ($file_system->exists($file_for_removal) && $output->is_verbose()) {
                $output->writeln($file_for_removal);
            }
            $file_system->remove($file_for_removal);
        }
        $output->writeln('mftf files removed from filesystem.');
        return self::SUCCESS_EXIT_CODE;
    }
}