# Copyright © Magento, Inc. All rights reserved.
# See COPYING.txt for license details.
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: src/Magento/FunctionalTestingFramework
    envs: etc/_envs
    output: tests/_output
settings:
    silent: true
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Magento\Functional_Testing_Framework\Codeception\Subscriber\Console
        - Magento\Functional_Testing_Framework\Extension\Test_Context_Extension
        - Qameta\Allure\Codeception\Allure_Codeception
    config:
        Qameta\Allure\Codeception\Allure_Codeception:
            deletePreviousResults: false
            outputDirectory: allure-results
            ignoredAnnotations:
                - env
                - zephyrId
                - useCaseId
        Magento\Functional_Testing_Framework\Extension\Test_Context_Extension:
            driver: \Magento\Functional_Testing_Framework\Module\Magento_Web_Driver
params:
    - .env
